#!/bin/sh

# cvs-authors
# http://www.sqlite.org/cvstrac/userlist

CURRENT_BRANCH=$(git branch | sed -ne 's|^\*[[:space:]]\(.*\)|\1|p')

git checkout cvs
git cvsimport -v -k -A ./cvs-authors -o cvs -d :pserver:anonymous@www.sqlite.org:/sqlite sqlite

if [ -n "$CURRENT_BRANCH" ]; then
	git checkout $CURRENT_BRANCH
fi
