#!/usr/make
#
# Makefile for SQLite Documentation
#

#### The toplevel directory of the documentation source.
#
DOC = .

#### The toplevel directory of the program source code.
#
SRC = ../sqlite

#### Pointer to the sqlite3.c amalgamation source file
#
SQLITE3C = ../bld/sqlite3.c

#### The toplevel directory of the TH3 test harness sources
#    Leave blank if TH3 is not available.
#
TH3 =

#### A C-compiler for building utility programs to run locally
#
CC = gcc -g -Wall

#### The TCL command shell
#
TCLSH = tclsh

#### Which "awk" program provides nawk compatibilty
#
# NAWK = nawk
NAWK = awk

# You should not have to change anything below this line
###############################################################################
include $(DOC)/main.mk
