#!/usr/make
#
# Makefile for SQLite Documentation
#

#### The toplevel directory of the documentation source.
#
DOC = .

#### The toplevel directory of the program source code.
#
SRC = ../sqlite

#### Which "awk" program provides nawk compatibilty
#
# NAWK = nawk
NAWK = awk

# You should not have to change anything below this line
###############################################################################
include $(DOC)/main.mk
